Dev hotspot checkout
CSC485A-Slacker/slacker pull request #59
Opened 2022-03-29 04:00 UTC by brendanmicetich

Added checkout logic and UI to switch "Check In" to "Check Out" in PinInfoOverlay. Also added toast notifications for all checkin/checkout scenarios.

2022-03-29 05:42 UTC, RanHuii requested changes
I check out from a spot and the spot disappears. Shouldn't it become a normal pin and stay on the map?

2022-03-29 05:42 UTC, RanHuii commented on src/components/PinInfoOverlay.tsx
> +        if (userId) {
Currently, I think users must be logged in to get to this step. However, in the future, It makes sense to allow users to view the map without signing in but no other actions.

2022-03-29 06:11 UTC, brendanmicetich commented
The functionality all works, but need to add the workaround to display the pins that Sam mentioned the other day.

2022-03-29 16:55 UTC, brendanmicetich commented on src/components/PinInfoOverlay.tsx
> +        if (userId) {
Since the userId can be undefined I have the check so that it can be used once it is confirmed not undefined. Then I figure it doesn't hurt to add a notification if they somehow aren't checked in by that point.

2022-03-29 16:57 UTC, brendanmicetich commented
> I check out from a spot and the spot disappears. Shouldn't it become a normal pin and stay on the map?

Just added the fix so that pins show up after checkout.

2022-03-29 20:04 UTC, RanHuii commented
I witnessed that the spot is still disappearing with auto checkout. So I checked in with 0 hours duration and after a few minutes, the spot disappears.

2022-03-29 21:35 UTC, brendanmicetich commented
Fixed the issue where the pins weren't rendering properly after auto-checkout.

2022-03-30 02:31 UTC, skosman approved these changes
Tested it with both private and public pins along with the auto checkout and it all worked great! Nice work

2022-03-31 03:43 UTC, merged